---
- name: Setup CVAT
  hosts: all
  vars:
    cvat_server_docker_image: "openvino/cvat_server"
    cvat_ui_docker_image: "openvino/cvat_ui"
  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: yes



